@baseURL = http://localhost:3333
@authToken = {{authentication.response.body.access_token}}

# @name create_account
POST {{baseURL}}/accounts
Content-Type: application/json

{
  "name": "Rodrigo Bighetti",
  "email": "rodrigo@stack2u.net",
  "password": "123456"
}


###

# @name authentication
POST {{baseURL}}/sessions
Content-Type: application/json

{  
  "email": "rodrigo@stack2u.net",
  "password": "123456"
}


###

# @name create_question
POST {{baseURL}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}
